Select * from Customer2

Select * from Product2

Select * from [Product Categories]

Select * from [Product Subcategories]

Select * from [Returns Data]

Select * from [Sales Data 2020]

Select * from [Sales Data 2021]

Select * from [Sales Data 2022]

Select * from [Territory Lookup]

select * from Total_sales

select * from TotalOrder

--Create Joint sales table
Select *
Into Total_sales
from [Sales Data 2020]
union all
Select * from [Sales Data 2021]
union all
Select * from [Sales Data 2022]

--Create total orders column
select Total_sales.*, ProductSKU, ProductPrice, (ProductPrice * OrderQuantity) 'TotalOrders'

from Total_sales
join Product2 on Total_sales.ProductKey = Product2.ProductKey

/* Retrieve the customers who have placed orders with a total amount greater than $10000.*/
Select CustomerKey, Sum (TotalOrders) 'TotalPrice'
into Customer_Price
from TotalOrder
Group By CustomerKey

Select FullName, TotalPrice
from Customer_Price
join Customer2 on Customer_Price.CustomerKey = Customer2.CustomerKey
where TotalPrice > 10000


/* Retrieve the total revenue and total orders generated by each product category */
Select  CategoryName, Count (OrderNumber) 'Total Order', Round(Sum (Profit), 2)'Total Revenue'
from Total_sales TS
join [Product2] P on TS.ProductKey = P.ProductKey
Join [Product Subcategories] PS on P.Product_SubcategoryKey = PS.ProductSubcategoryKey
Join [Product Categories] PC on PS.ProductCategoryKey__ = PC.ProductCategoryKey
Group by CategoryName


/* Retrieve the names of products, sub-categories and their categories for 
	products with a selling price greater than the average selling price of all 
	products */
--Get Average selling Price
Select Round(AVG (ProductPrice), 2)
from Product2

Select ProductName, SubcategoryName, CategoryName, ProductPrice
from Product2 P
Join [Product Subcategories] PS on P.Product_SubcategoryKey = PS.ProductSubcategoryKey
Join [Product Categories] PC on PS.ProductCategoryKey__ = PC.ProductCategoryKey
where ProductPrice > (Select Round(AVG (ProductPrice), 2)
						from Product2)


/* How many customers have placed orders in “Canada”? List the customer names */
Select *
from Total_sales TS
Join [Territory Lookup] TL on Ts.TerritoryKey = TL.SalesTerritoryKey
Join Customer2 C on Ts.CustomerKey = c.CustomerKey
Where Country = 'Canada'

Select Distinct FullName
from Total_sales TS
Join [Territory Lookup] TL on Ts.TerritoryKey = TL.SalesTerritoryKey
Join Customer2 C on Ts.CustomerKey = c.CustomerKey
Where Country = 'Canada'

--How mANY CUstomers placed order in canada
Select Count(Distinct FullName)
from Total_sales TS
Join [Territory Lookup] TL on Ts.TerritoryKey = TL.SalesTerritoryKey
Join Customer2 C on Ts.CustomerKey = c.CustomerKey
Where Country = 'Canada'

/* Find the 10 products that have been returned the most. How much money was generated by these products? */
Select ProductKey, Count(ReturnQuantity) 'ReturnTimes'
Into REturnTable
From [Returns Data]
Group by ProductKey
Order by 'ReturnTimes' DESC

Select TOP 10 ProductName, ReturnTimes, Profit, P.ProductKey 
from REturnTable RT
Join Product2 P on RT.ProductKey = p.ProductKey
Order by 'ReturnTimes' DESc


/* Get a list of customers who have placed orders in more than one territory */
Select CustomerKey, Count(Distinct SalesTerritoryKey) 'Number of Territories'
from Total_sales TS
left join [Territory Lookup] TL on TS.TerritoryKey = TL.SalesTerritoryKey
Group by CustomerKey
Having Count(Distinct SalesTerritoryKey) > 1

/*Retrieve the product names and their corresponding sub-categories for 
	products that have been ordered at least 10 times*/
Select TS.ProductKey 
from Total_sales TS
group by TS.ProductKey
Having Count(OrderQuantity) >= 10

Select ProductKey, ProductName, SubcategoryName 
from Product2 P
Join [Product Subcategories] PS on P.Product_SubcategoryKey = PS.ProductSubcategoryKey
Where ProductKey in (Select TS.ProductKey 
					from Total_sales TS
					group by TS.ProductKey
					Having Count(OrderQuantity) >= 10)


/* List the customer names who have placed orders after 2021. What is the distribution of their occupation? */
Select Distinct FullName, Occupation
frOm [Sales Data 2022] SD
Left Join Customer2 C on SD.CustomerKey = C.CustomerKey

Select Distinct FullName, Occupation
Into OccupationT
frOm [Sales Data 2022] SD
Left Join Customer2 C on SD.CustomerKey = C.CustomerKey


--Their distribution of occupation
Select Occupation, Count(Occupation) 'distribution'
frOm OccupationT
Group by Occupation


/* Get a list of products and their corresponding order quantities for products that have been ordered at least 5 times. */
Select ProductKey, COUNT(OrderQuantity)'Number of Orders'
from Total_sales
Group by ProductKey
Having COUNT(OrderQuantity) >= 5 

Select ProductName, COUNT(OrderQuantity)'Number of Orders'
from Total_sales TS
Join Product2 P on TS.ProductKey = P.ProductKey
where TS.ProductKey in (Select ProductKey
					from Total_sales
					Group by ProductKey
					Having COUNT(OrderQuantity) >= 5 )
Group by ProductName
Order by 'Number of Orders' DESC


/* Retrieve the product names that start with the letter "C" or “H” and are from the "Clothing" category. */
Select *
into Cloth_ing
from Product2 P
Join [Product Subcategories] PS on P.Product_SubcategoryKey = PS.ProductSubcategoryKey
Join [Product Categories] PC on PS.ProductCategoryKey__ = PC.ProductCategoryKey
where CategoryName = 'Clothing' 

Select ProductName from Cloth_ing
Where ProductName like 'C%' or ProductName like 'H%'


/* Retrieve the product names that have been ordered in the ‘United States’ or "Australia". */
Select Distinct ProductName
from Product2 P
join Total_sales Ts on P.ProductKey = TS.ProductKey
join [Territory Lookup] TL on TS.TerritoryKey = TL.SalesTerritoryKey
Where Country = 'United States' or Country = 'Australia'


-/* Find the customer names who have placed orders with a total amount greater than the average total amount of orders. */
Select Distinct CustomerKey, Count(OrderQuantity) 'number of orders'
into OrdersbyCkey
from Total_sales
Group By CustomerKey

Select AVG([number of orders])
from OrdersbyCkey

Select FullName, [number of orders]
From OrdersbyCkey OC
Join Customer2 C on Oc.CustomerKey = C.CustomerKey
Where [number of orders] > (Select AVG([number of orders])
							from OrdersbyCkey)


/* Retrieve the top 5 customers who have placed the highest number of orders, along with their order counts */
Select TOP 5 FullName, [number of orders]
From OrdersbyCkey OC
Join Customer2 C on Oc.CustomerKey = C.CustomerKey
Order by [number of orders] DESC


/* List the customers who have placed orders within the last 6 months (consider the last date in the data) */
Select Distinct FullName
from Total_sales TS
Join Customer2 C on TS.CustomerKey = C.CustomerKey
Where OrderDate like '2022%'


/* We want to reach out to our best customers in 2022. Can you get emails of Top 50 customers based on revenue? */
Select distinct  TOP 50 CustomerKey, Sum(OrderPrice) 'Total order'
INTO TOP50C
from TotalOrder
Group by CustomerKey
Order by 'Total order' DESC

SELECT FullName, EmailAddress, [Total order]
FROM TOP50C TT
JOIN Customer2 C ON TT.CustomerKey = C.CustomerKey
Order by 'Total order' DESC